name: Build plugin

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Build plugin
        run: |
          ./gradlew buildPlugin
